# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0b3c241e1f5712c0b2ec3e1b1527746e23b4c7b46a334010f33bb7b1ef7617372cb2aef727b1b95e22f3af785fe8f929b49f160725c4c2f09765d8bfedc6cb

test:
  secret_key_base: 490549df0cef61dc2f0eb4a971dcf65dc52bc8c0070faf97d961ec93446acb6c9ea66c1d0f2bf7f4467e5ab2744f0e2b173613d56c1640a3f9ac778bdbb00d99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
